import { LLM_MODELS } from "@/lib/config";
import type { LlmProvider } from "@/lib/providers/types";
import type { DescriptionMode } from "@/lib/types/enums";
import { deriveChapters, renderChapterList } from "./chapters";
import type { PackagingContext } from "./context";

/**
 * Description generation — spec §5.11. Three modes (informative / narrative /
 * seo) generated by Sonnet from the script + frame, with optional workspace
 * template `{{slot}}` filling. Output is plain text ready for the YouTube
 * description box.
 */

const MAX_DESCRIPTION_CHARS = 4_800; // YouTube caps descriptions at 5,000.

const MODE_BRIEFS: Record<DescriptionMode, string> = {
  informative:
    "Write a factual, scannable YouTube description. Open with 1-2 sentences saying exactly what the video covers and for whom. Follow with a short bulleted list of what the viewer will learn. No hype, no emojis in the opening line.",
  narrative:
    "Write a story-led YouTube description. Open mid-tension, mirroring the video's hook without spoiling the payoff. 2-3 short paragraphs in the creator's voice, first person. End with one line inviting the viewer to watch to the end.",
  seo: "Write a search-optimized YouTube description. The first 150 characters must read naturally while containing the primary keyword. Weave the keyword list into fluent sentences (never a bare keyword dump), and close with 2-3 related phrases viewers search for.",
};

export function buildDescriptionPrompt(ctx: PackagingContext, mode: DescriptionMode): string {
  const sectionSummary = ctx.sections
    .map((s) => `- [${s.kind}] ${s.heading}: ${s.body.slice(0, 220)}`)
    .join("\n");
  const frameLines =
    ctx.frame === null
      ? "No frame chosen."
      : [
          `Angle: ${ctx.frame.angle}`,
          `Format: ${ctx.frame.format} · Outcome: ${ctx.frame.outcome}`,
          `Audience: ${ctx.frame.audienceSegment}`,
          `Tone: ${ctx.frame.tone}`,
          `Keywords: ${ctx.frame.keywords.join(", ")}`,
        ].join("\n");
  return [
    `Video title (working): ${ctx.projectTitle}`,
    "",
    "Frame:",
    frameLines,
    "",
    `Channel niche keywords: ${ctx.nicheKeywords.join(", ")}`,
    "",
    "Script sections:",
    sectionSummary,
    "",
    `Task: ${MODE_BRIEFS[mode]}`,
    `Hard limit: ${MAX_DESCRIPTION_CHARS} characters. Return ONLY the description text — no preamble, no markdown fences.`,
  ].join("\n");
}

export interface DescriptionTemplateInput {
  name: string;
  /** Body with `{{slots}}`. */
  body: string;
}

/**
 * Fill the known `{{slots}}` of a description template. Unknown slots are
 * left in place so the user can fill them in the editor.
 *
 * Known slots: {{summary}} (the generated description), {{title}},
 * {{chapters}} (derived chapter list), {{keywords}}.
 */
export function fillDescriptionTemplate(
  template: DescriptionTemplateInput,
  ctx: PackagingContext,
  summary: string,
): string {
  const chapters = renderChapterList(deriveChapters(ctx.sections));
  const keywords = (ctx.frame?.keywords ?? ctx.nicheKeywords).join(", ");
  const slots: Record<string, string> = {
    summary,
    title: ctx.projectTitle,
    chapters,
    keywords,
  };
  return template.body.replace(/\{\{\s*(\w+)\s*\}\}/g, (match, slot: string) => {
    const value = slots[slot];
    return value ?? match;
  });
}

/**
 * Generate a description body. Sonnet (spec §2: descriptions are a drafting
 * task, not a classification task). When a template is provided, the LLM
 * output fills its {{summary}} slot; otherwise the output is the body.
 */
export async function generateDescriptionBody(
  llm: LlmProvider,
  ctx: PackagingContext,
  mode: DescriptionMode,
  template: DescriptionTemplateInput | null = null,
): Promise<string> {
  const response = await llm.complete({
    model: LLM_MODELS.sonnet,
    system:
      "You are a YouTube packaging writer. You write descriptions that are honest to the script's content and formatted for the YouTube description box (plain text, short paragraphs).",
    prompt: buildDescriptionPrompt(ctx, mode),
    maxTokens: 1_200,
    temperature: 0.7,
  });
  const summary = response.text.trim().slice(0, MAX_DESCRIPTION_CHARS);
  if (template === null) {
    return summary;
  }
  return fillDescriptionTemplate(template, ctx, summary).slice(0, MAX_DESCRIPTION_CHARS * 2);
}
